In [1]:
"""Q6. What happens when a numpy array is combined with a single-value operand 
(a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?"""
import numpy as np
a=np.arange(9).reshape(3,3)
print(a)
print()
print(a+1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
a+=1
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a*=2
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
import numpy as np
name = np.array(['ram', 'mohan', 'shiva'])
name

array(['ram', 'mohan', 'shiva'], dtype='<U5')

In [6]:
name[name=='ram']='undertaker'
print(name)

['under' 'mohan' 'shiva']


In [8]:
a1=a
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
a2=a+2
a2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [10]:
a1+a2

array([[ 6, 10, 14],
       [18, 22, 26],
       [30, 34, 38]])

In [11]:
a1*a2

array([[  8,  24,  48],
       [ 80, 120, 168],
       [224, 288, 360]])

In [16]:
"Q10. What is the best way to use a Boolean array to mask another array?"

y = np.array([True,True,False,True])          
x = np.array([1,2,3,4])         
m = np.ma.masked_where(x>2,y)  
print(list(m))
print(m.ndim)

[True, True, masked, masked]
1


TypeError: only size-1 arrays can be converted to Python scalars