In [2]:
"""Q5. Compare and contrast the three types of array multiplication between two 
numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays"""
import numpy as np

In [3]:
a1=np.array([[1,2,3],[4,5,6],[6,7,8]])
a2=np.array([[10,20,30],[40,50,60],[60,70,80]])

In [4]:
print(a1)
print()
print(a2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]

[[10 20 30]
 [40 50 60]
 [60 70 80]]


In [5]:
#standard multiplication
a1*a2

array([[ 10,  40,  90],
       [160, 250, 360],
       [360, 490, 640]])

In [7]:
np.dot(a1,a2)

array([[ 270,  330,  390],
       [ 600,  750,  900],
       [ 820, 1030, 1240]])

In [8]:
np.outer(a1,a2)

array([[ 10,  20,  30,  40,  50,  60,  60,  70,  80],
       [ 20,  40,  60,  80, 100, 120, 120, 140, 160],
       [ 30,  60,  90, 120, 150, 180, 180, 210, 240],
       [ 40,  80, 120, 160, 200, 240, 240, 280, 320],
       [ 50, 100, 150, 200, 250, 300, 300, 350, 400],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 70, 140, 210, 280, 350, 420, 420, 490, 560],
       [ 80, 160, 240, 320, 400, 480, 480, 560, 640]])